# Generated by Django 5.1.6 on 2025-02-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tag_bookmark_lesson_bookmarks_users_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.comment'),
        ),
    ]
